create table if not exists public.admins (
  email text primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.content (
  locale text not null check (locale in ('en', 'vi')),
  page text not null check (page in ('home', 'projects')),
  translations jsonb not null default '{}'::jsonb,
  meta jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  primary key (locale, page)
);

alter table public.admins enable row level security;
alter table public.content enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admins
    where email = auth.jwt() ->> 'email'
  );
$$;

drop policy if exists "Public can read portfolio content" on public.content;
create policy "Public can read portfolio content"
on public.content
for select
using (true);

drop policy if exists "Portfolio admins can insert content" on public.content;
create policy "Portfolio admins can insert content"
on public.content
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Portfolio admins can update content" on public.content;
create policy "Portfolio admins can update content"
on public.content
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Portfolio admins can delete content" on public.content;
create policy "Portfolio admins can delete content"
on public.content
for delete
to authenticated
using (public.is_admin());

drop trigger if exists set_content_updated_at on public.content;
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_content_updated_at
before update on public.content
for each row
execute function public.set_updated_at();

-- After creating your Supabase Auth user, add your admin email here:
insert into public.admins (email) values ('lebuitantruong@gmail.com');

create table if not exists public.profile (
  id boolean primary key default true check (id),
  full_name text not null,
  title text not null,
  email text,
  phone text,
  github_url text,
  current_company text,
  current_position text,
  current_start_date date,
  education_school text,
  education_major text,
  education_start_date date,
  education_end_date date,
  gpa text,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.profile_translations (
  profile_id boolean not null references public.profile(id) on delete cascade,
  locale text not null check (locale in ('en', 'vi')),
  professional_summary text not null,
  primary key (profile_id, locale)
);

create table if not exists public.skill_categories (
  slug text primary key,
  sort_order integer not null default 0
);

create table if not exists public.skill_category_translations (
  category_slug text not null references public.skill_categories(slug) on delete cascade,
  locale text not null check (locale in ('en', 'vi')),
  name text not null,
  primary key (category_slug, locale)
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  category_slug text not null references public.skill_categories(slug) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  unique (category_slug, name)
);

create table if not exists public.experiences (
  slug text primary key,
  company text not null,
  role text not null,
  start_date date not null,
  end_date date,
  is_current boolean not null default false,
  sort_order integer not null default 0,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.experience_translations (
  experience_slug text not null references public.experiences(slug) on delete cascade,
  locale text not null check (locale in ('en', 'vi')),
  summary text not null,
  primary key (experience_slug, locale)
);

create table if not exists public.experience_bullets (
  id bigint generated by default as identity primary key,
  experience_slug text not null references public.experiences(slug) on delete cascade,
  locale text not null check (locale in ('en', 'vi')),
  body text not null,
  sort_order integer not null default 0,
  unique (experience_slug, locale, sort_order)
);

create table if not exists public.projects (
  slug text primary key,
  name text not null,
  customer text,
  role text not null default 'Mobile Developer',
  team_size_min integer,
  team_size_max integer,
  start_date date,
  end_date date,
  is_current boolean not null default false,
  project_type text,
  featured boolean not null default false,
  sort_order integer not null default 0,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_translations (
  project_slug text not null references public.projects(slug) on delete cascade,
  locale text not null check (locale in ('en', 'vi')),
  eyebrow text,
  short_description text not null,
  summary_title text,
  summary_body text,
  primary key (project_slug, locale)
);

create table if not exists public.project_responsibilities (
  id bigint generated by default as identity primary key,
  project_slug text not null references public.projects(slug) on delete cascade,
  locale text not null check (locale in ('en', 'vi')),
  title text,
  body text not null,
  sort_order integer not null default 0,
  unique (project_slug, locale, sort_order)
);

create table if not exists public.project_modules (
  id bigint generated by default as identity primary key,
  project_slug text not null references public.projects(slug) on delete cascade,
  locale text not null check (locale in ('en', 'vi')),
  name text not null,
  is_core boolean not null default false,
  sort_order integer not null default 0,
  unique (project_slug, locale, sort_order)
);

create table if not exists public.technologies (
  slug text primary key,
  name text not null,
  category text,
  sort_order integer not null default 0
);

create table if not exists public.project_technologies (
  project_slug text not null references public.projects(slug) on delete cascade,
  technology_slug text not null references public.technologies(slug) on delete cascade,
  sort_order integer not null default 0,
  primary key (project_slug, technology_slug)
);

create table if not exists public.project_links (
  id bigint generated by default as identity primary key,
  project_slug text not null references public.projects(slug) on delete cascade,
  label text not null,
  url text not null,
  sort_order integer not null default 0
);

create index if not exists idx_projects_sort
on public.projects (sort_order, start_date desc);

create index if not exists idx_project_translations_locale
on public.project_translations (locale);

create index if not exists idx_project_responsibilities_project_locale
on public.project_responsibilities (project_slug, locale, sort_order);

create index if not exists idx_project_modules_project_locale
on public.project_modules (project_slug, locale, sort_order);

alter table public.profile enable row level security;
alter table public.profile_translations enable row level security;
alter table public.skill_categories enable row level security;
alter table public.skill_category_translations enable row level security;
alter table public.skills enable row level security;
alter table public.experiences enable row level security;
alter table public.experience_translations enable row level security;
alter table public.experience_bullets enable row level security;
alter table public.projects enable row level security;
alter table public.project_translations enable row level security;
alter table public.project_responsibilities enable row level security;
alter table public.project_modules enable row level security;
alter table public.technologies enable row level security;
alter table public.project_technologies enable row level security;
alter table public.project_links enable row level security;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'profile',
    'profile_translations',
    'skill_categories',
    'skill_category_translations',
    'skills',
    'experiences',
    'experience_translations',
    'experience_bullets',
    'projects',
    'project_translations',
    'project_responsibilities',
    'project_modules',
    'technologies',
    'project_technologies',
    'project_links'
  ]
  loop
    execute format('drop policy if exists "Public can read %I" on public.%I', table_name, table_name);
    execute format('create policy "Public can read %I" on public.%I for select using (true)', table_name, table_name);

    execute format('drop policy if exists "Portfolio admins can insert %I" on public.%I', table_name, table_name);
    execute format('create policy "Portfolio admins can insert %I" on public.%I for insert to authenticated with check (public.is_admin())', table_name, table_name);

    execute format('drop policy if exists "Portfolio admins can update %I" on public.%I', table_name, table_name);
    execute format('create policy "Portfolio admins can update %I" on public.%I for update to authenticated using (public.is_admin()) with check (public.is_admin())', table_name, table_name);

    execute format('drop policy if exists "Portfolio admins can delete %I" on public.%I', table_name, table_name);
    execute format('create policy "Portfolio admins can delete %I" on public.%I for delete to authenticated using (public.is_admin())', table_name, table_name);
  end loop;
end $$;

drop trigger if exists set_profile_updated_at on public.profile;
create trigger set_profile_updated_at
before update on public.profile
for each row
execute function public.set_updated_at();

drop trigger if exists set_experiences_updated_at on public.experiences;
create trigger set_experiences_updated_at
before update on public.experiences
for each row
execute function public.set_updated_at();

drop trigger if exists set_projects_updated_at on public.projects;
create trigger set_projects_updated_at
before update on public.projects
for each row
execute function public.set_updated_at();

create or replace view public.project_cards as
select
  p.slug,
  p.name,
  p.customer,
  p.role,
  p.team_size_min,
  p.team_size_max,
  p.start_date,
  p.end_date,
  p.is_current,
  p.project_type,
  p.featured,
  p.sort_order,
  t.locale,
  t.eyebrow,
  t.short_description,
  t.summary_title,
  t.summary_body,
  coalesce(
    jsonb_agg(
      distinct jsonb_build_object(
        'slug', tech.slug,
        'name', tech.name,
        'category', tech.category,
        'sortOrder', pt.sort_order
      )
    ) filter (where tech.slug is not null),
    '[]'::jsonb
  ) as technologies
from public.projects p
join public.project_translations t on t.project_slug = p.slug
left join public.project_technologies pt on pt.project_slug = p.slug
left join public.technologies tech on tech.slug = pt.technology_slug
group by p.slug, t.locale, t.eyebrow, t.short_description, t.summary_title, t.summary_body;

create or replace function public.get_projects(requested_locale text default 'en')
returns jsonb
language sql
stable
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'slug', p.slug,
        'name', p.name,
        'customer', p.customer,
        'role', p.role,
        'teamSize', case
          when p.team_size_min is null then null
          when p.team_size_max is null or p.team_size_max = p.team_size_min then to_jsonb(p.team_size_min)
          else jsonb_build_object('min', p.team_size_min, 'max', p.team_size_max)
        end,
        'timeline', jsonb_build_object(
          'startDate', p.start_date,
          'endDate', p.end_date,
          'isCurrent', p.is_current
        ),
        'type', p.project_type,
        'featured', p.featured,
        'eyebrow', coalesce(t.eyebrow, fallback_t.eyebrow),
        'shortDescription', coalesce(t.short_description, fallback_t.short_description),
        'summaryTitle', coalesce(t.summary_title, fallback_t.summary_title),
        'summaryBody', coalesce(t.summary_body, fallback_t.summary_body),
        'technologies', coalesce(techs.items, '[]'::jsonb),
        'responsibilities', coalesce(responsibilities.items, '[]'::jsonb),
        'modules', coalesce(modules.items, '[]'::jsonb),
        'links', coalesce(links.items, '[]'::jsonb)
      )
      order by p.sort_order
    ),
    '[]'::jsonb
  )
  from public.projects p
  left join public.project_translations t
    on t.project_slug = p.slug and t.locale = requested_locale
  left join public.project_translations fallback_t
    on fallback_t.project_slug = p.slug and fallback_t.locale = 'en'
  left join lateral (
    select jsonb_agg(
      jsonb_build_object('slug', tech.slug, 'name', tech.name, 'category', tech.category)
      order by pt.sort_order
    ) as items
    from public.project_technologies pt
    join public.technologies tech on tech.slug = pt.technology_slug
    where pt.project_slug = p.slug
  ) techs on true
  left join lateral (
    select jsonb_agg(
      jsonb_build_object('title', r.title, 'body', r.body)
      order by r.sort_order
    ) as items
    from public.project_responsibilities r
    where r.project_slug = p.slug and r.locale = requested_locale
  ) responsibilities on true
  left join lateral (
    select jsonb_agg(
      jsonb_build_object('name', m.name, 'isCore', m.is_core)
      order by m.sort_order
    ) as items
    from public.project_modules m
    where m.project_slug = p.slug and m.locale = requested_locale
  ) modules on true
  left join lateral (
    select jsonb_agg(
      jsonb_build_object('label', l.label, 'url', l.url)
      order by l.sort_order
    ) as items
    from public.project_links l
    where l.project_slug = p.slug
  ) links on true;
$$;

insert into public.profile (
  id,
  full_name,
  title,
  email,
  phone,
  github_url,
  current_company,
  current_position,
  current_start_date,
  education_school,
  education_major,
  education_start_date,
  education_end_date,
  gpa
) values (
  true,
  'Le Bui Tan Truong',
  'Mobile Developer (Flutter / React Native)',
  'lebuitantruong@gmail.com',
  '0328467924',
  'https://github.com/lbtt2801',
  'Dai Phat Solutions',
  'Mobile Developer',
  '2024-02-01',
  'Ho Chi Minh City University of Industry and Trade (HUIT)',
  'Software Engineer',
  '2020-10-01',
  '2024-11-01',
  '3.29/4'
) on conflict (id) do update set
  full_name = excluded.full_name,
  title = excluded.title,
  email = excluded.email,
  phone = excluded.phone,
  github_url = excluded.github_url,
  current_company = excluded.current_company,
  current_position = excluded.current_position,
  current_start_date = excluded.current_start_date,
  education_school = excluded.education_school,
  education_major = excluded.education_major,
  education_start_date = excluded.education_start_date,
  education_end_date = excluded.education_end_date,
  gpa = excluded.gpa;

insert into public.profile_translations (profile_id, locale, professional_summary) values
(true, 'en', 'Mobile Developer with hands-on experience building scalable mobile applications using Flutter and React Native. Experienced in production-ready systems across POS, e-commerce, booking platforms, government applications, and complex business workflows.'),
(true, 'vi', 'Mobile Developer có kinh nghiệm thực chiến xây dựng ứng dụng mobile có khả năng mở rộng bằng Flutter và React Native. Có kinh nghiệm với hệ thống production-ready trong POS, e-commerce, booking, ứng dụng chính phủ và các workflow nghiệp vụ phức tạp.')
on conflict (profile_id, locale) do update set professional_summary = excluded.professional_summary;

insert into public.skill_categories (slug, sort_order) values
('mobile-technologies', 1),
('programming-languages', 2),
('state-management', 3),
('mobile-features', 4),
('tools-debugging', 5),
('soft-skills', 6)
on conflict (slug) do update set sort_order = excluded.sort_order;

insert into public.skill_category_translations (category_slug, locale, name) values
('mobile-technologies', 'en', 'Mobile Technologies'),
('mobile-technologies', 'vi', 'Công nghệ Mobile'),
('programming-languages', 'en', 'Programming Languages'),
('programming-languages', 'vi', 'Ngôn ngữ lập trình'),
('state-management', 'en', 'State Management'),
('state-management', 'vi', 'Quản lý State'),
('mobile-features', 'en', 'Mobile Features'),
('mobile-features', 'vi', 'Tính năng Mobile'),
('tools-debugging', 'en', 'Tools & Debugging'),
('tools-debugging', 'vi', 'Công cụ & Debugging'),
('soft-skills', 'en', 'Soft Skills'),
('soft-skills', 'vi', 'Kỹ năng mềm')
on conflict (category_slug, locale) do update set name = excluded.name;

insert into public.skills (category_slug, name, sort_order) values
('mobile-technologies', 'Flutter', 1),
('mobile-technologies', 'React Native', 2),
('mobile-technologies', 'Jetpack Compose', 3),
('programming-languages', 'Dart', 1),
('programming-languages', 'JavaScript', 2),
('programming-languages', 'TypeScript', 3),
('programming-languages', 'Kotlin', 4),
('state-management', 'BLoC', 1),
('state-management', 'Redux', 2),
('mobile-features', 'Firebase', 1),
('mobile-features', 'RESTful APIs', 2),
('mobile-features', 'Maps & Location Services', 3),
('mobile-features', 'POS Printing', 4),
('tools-debugging', 'Git', 1),
('tools-debugging', 'DevTools', 2),
('tools-debugging', 'React Native Debugger', 3),
('tools-debugging', 'Flipper', 4),
('soft-skills', 'Problem-Solving', 1),
('soft-skills', 'Debugging', 2),
('soft-skills', 'AI-assisted Development', 3),
('soft-skills', 'Teamwork', 4),
('soft-skills', 'Self-learning', 5)
on conflict (category_slug, name) do update set sort_order = excluded.sort_order;

insert into public.experiences (slug, company, role, start_date, end_date, is_current, sort_order) values
('dai-phat-solutions', 'Dai Phat Solutions', 'Mobile Developer', '2024-02-01', null, true, 1),
('s3corp', 'Sunrise Software Solutions Corporation (S3Corp)', 'Android Developer', '2023-07-01', '2024-01-31', false, 2)
on conflict (slug) do update set
  company = excluded.company,
  role = excluded.role,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  is_current = excluded.is_current,
  sort_order = excluded.sort_order;

insert into public.experience_translations (experience_slug, locale, summary) values
('dai-phat-solutions', 'en', 'Develop and maintain production mobile applications using Flutter and React Native for business management systems, booking platforms, and enterprise applications.'),
('dai-phat-solutions', 'vi', 'Phát triển và bảo trì ứng dụng mobile production bằng Flutter và React Native cho hệ thống quản lý doanh nghiệp, booking platforms và enterprise applications.'),
('s3corp', 'en', 'Developed Android applications using Kotlin and Jetpack Compose, implemented user interfaces based on business requirements, integrated RESTful APIs, and collaborated with cross-functional teams.'),
('s3corp', 'vi', 'Phát triển ứng dụng Android bằng Kotlin và Jetpack Compose, triển khai giao diện theo yêu cầu nghiệp vụ, tích hợp RESTful APIs và phối hợp với cross-functional teams.')
on conflict (experience_slug, locale) do update set summary = excluded.summary;

insert into public.experience_bullets (experience_slug, locale, body, sort_order) values
('dai-phat-solutions', 'en', 'Developed and maintained scalable mobile applications serving real business operations.', 1),
('dai-phat-solutions', 'en', 'Applied BLoC and Redux to improve code structure and maintainability.', 2),
('dai-phat-solutions', 'en', 'Built reusable UI components following UI/UX specifications and responsive design principles.', 3),
('dai-phat-solutions', 'en', 'Integrated RESTful APIs, implemented complex business workflows, fixed production issues, and improved stability.', 4),
('dai-phat-solutions', 'vi', 'Phát triển và bảo trì ứng dụng mobile có khả năng mở rộng phục vụ nghiệp vụ kinh doanh thực tế.', 1),
('dai-phat-solutions', 'vi', 'Áp dụng BLoC và Redux để cải thiện cấu trúc code và khả năng bảo trì.', 2),
('dai-phat-solutions', 'vi', 'Xây dựng reusable UI components theo UI/UX specifications và responsive design principles.', 3),
('dai-phat-solutions', 'vi', 'Tích hợp RESTful APIs, triển khai business workflows phức tạp, xử lý lỗi production và cải thiện độ ổn định.', 4),
('s3corp', 'en', 'Developed Android applications using Kotlin following MVVM/MVP architecture.', 1),
('s3corp', 'en', 'Implemented user interfaces based on UI/UX designs and Business Analysis documents.', 2),
('s3corp', 'en', 'Built data models, application logic, and RESTful API integrations for backend communication.', 3),
('s3corp', 'en', 'Collaborated with team members to deliver small- to medium-sized projects on schedule.', 4),
('s3corp', 'vi', 'Phát triển ứng dụng Android bằng Kotlin theo kiến trúc MVVM/MVP.', 1),
('s3corp', 'vi', 'Triển khai giao diện dựa trên UI/UX designs và Business Analysis documents.', 2),
('s3corp', 'vi', 'Xây dựng data models, application logic và tích hợp RESTful APIs để giao tiếp backend.', 3),
('s3corp', 'vi', 'Phối hợp với team để bàn giao các dự án nhỏ đến trung bình đúng tiến độ.', 4)
on conflict (experience_slug, locale, sort_order) do update set body = excluded.body;

insert into public.technologies (slug, name, category, sort_order) values
('flutter', 'Flutter', 'mobile', 1),
('dart', 'Dart', 'language', 2),
('react-native', 'React Native', 'mobile', 3),
('javascript', 'JavaScript', 'language', 4),
('typescript', 'TypeScript', 'language', 5),
('kotlin', 'Kotlin', 'language', 6),
('jetpack-compose', 'Jetpack Compose', 'mobile', 7),
('bloc', 'BLoC', 'state', 8),
('redux', 'Redux', 'state', 9),
('mvvm', 'MVVM', 'architecture', 10),
('mvp', 'MVP', 'architecture', 11),
('clean-architecture', 'Clean Architecture', 'architecture', 12),
('firebase', 'Firebase', 'backend', 13),
('fcm', 'FCM', 'backend', 14),
('restful-apis', 'RESTful APIs', 'integration', 15),
('git', 'Git', 'tool', 16),
('maps-location', 'Maps & Location Services', 'feature', 17),
('pos-printing', 'POS Printing', 'feature', 18),
('retrofit', 'Retrofit', 'integration', 19),
('coroutines', 'Coroutines', 'architecture', 20),
('flow', 'Flow', 'architecture', 21)
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  sort_order = excluded.sort_order;

insert into public.projects (
  slug,
  name,
  customer,
  role,
  team_size_min,
  team_size_max,
  start_date,
  end_date,
  is_current,
  project_type,
  featured,
  sort_order
) values
('dp247', 'DP247', 'Shop owners, businesses', 'Mobile Developer', 3, 3, '2024-03-01', null, true, 'POS platform', true, 1),
('huit-edu', 'HUIT EDU', 'Lecturers of Ho Chi Minh City University of Industry and Trade (HUIT)', 'Mobile Developer', 4, 4, '2024-02-01', null, true, 'University operations app', false, 2),
('huit-student', 'HUIT STUDENT', 'Students at Ho Chi Minh City University of Industry and Trade (HUIT)', 'Mobile Developer', 3, 3, '2025-08-01', null, true, 'Student platform', false, 3),
('my-dp247', 'MY DP247', 'Customers using the services of the DP247 application', 'Mobile Developer', 3, 3, '2024-05-01', '2024-12-31', false, 'Consumer commerce app', false, 4),
('dc40', 'DC4.0', 'VNPT MEDIA', 'Mobile Developer', 2, 3, '2024-05-01', null, true, 'Community management platform', false, 5),
('hearme', 'HearMe App', null, 'Android Developer', 2, 2, '2023-07-01', '2023-09-30', false, 'Music streaming app', false, 6),
('reading-habit', 'Reading Habit', 'KUN LOF', 'Android Developer', 4, 4, '2023-10-01', '2024-01-31', false, 'Children reading platform', false, 7)
on conflict (slug) do update set
  name = excluded.name,
  customer = excluded.customer,
  role = excluded.role,
  team_size_min = excluded.team_size_min,
  team_size_max = excluded.team_size_max,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  is_current = excluded.is_current,
  project_type = excluded.project_type,
  featured = excluded.featured,
  sort_order = excluded.sort_order;

insert into public.project_translations (project_slug, locale, eyebrow, short_description, summary_title, summary_body) values
('dp247', 'en', 'Featured project', 'POS platform for restaurants and retail operations.', 'Digital transformation platform for restaurants and retail stores.', 'DP247 supports sales management, inventory, human resources, order workflows, billing, promotions, loyalty programs, stock control, and receipt printing for shop owners and business teams.'),
('dp247', 'vi', 'Dự án nổi bật', 'Nền tảng POS cho vận hành nhà hàng và bán lẻ.', 'Nền tảng chuyển đổi số cho nhà hàng và cửa hàng bán lẻ.', 'DP247 hỗ trợ quản lý bán hàng, tồn kho, nhân sự, quy trình đơn hàng, thanh toán, khuyến mãi, chương trình khách hàng thân thiết, kiểm soát kho và in hóa đơn cho chủ cửa hàng và đội ngũ kinh doanh.'),
('huit-edu', 'en', 'Flutter university operations', 'Lecturer operations app for attendance, tasks, HR, and workflows.', 'Daily operations platform for lecturers at HUIT.', 'Supports task management, attendance tracking, teaching activities, HR processes, lecturer management, and internal workflow modules.'),
('huit-edu', 'vi', 'Vận hành đại học bằng Flutter', 'Ứng dụng vận hành cho giảng viên: chấm công, công việc, nhân sự và workflow.', 'Nền tảng vận hành hằng ngày cho giảng viên HUIT.', 'Hỗ trợ quản lý công việc, chấm công, hoạt động giảng dạy, quy trình nhân sự, quản lý giảng viên và các module workflow nội bộ.'),
('huit-student', 'en', 'Flutter student platform', 'Student feedback, survey, and teaching quality evaluation app.', null, 'A mobile application for HUIT students to submit feedback, participate in surveys, and evaluate teaching quality and university activities.'),
('huit-student', 'vi', 'Nền tảng sinh viên Flutter', 'Ứng dụng phản hồi, khảo sát và đánh giá chất lượng giảng dạy cho sinh viên.', null, 'Ứng dụng mobile cho sinh viên HUIT gửi phản hồi, tham gia khảo sát và đánh giá chất lượng giảng dạy cũng như hoạt động của trường.'),
('my-dp247', 'en', 'React Native consumer app', 'Consumer shopping, food ordering, promotions, and store discovery.', null, 'A consumer app in the DP247 ecosystem for online shopping, food ordering, promotions, and store discovery.'),
('my-dp247', 'vi', 'Ứng dụng tiêu dùng React Native', 'Ứng dụng mua sắm, đặt món, khuyến mãi và tìm kiếm cửa hàng.', null, 'Ứng dụng tiêu dùng trong hệ sinh thái DP247 hỗ trợ mua sắm online, đặt món, khuyến mãi và tìm cửa hàng.'),
('dc40', 'en', 'React Native community platform', 'Community management platform for neighborhood and residential operations.', null, 'A VNPT Media community management platform for neighborhood and residential area operations, including meetings, tasks, households, residents, documents, evaluations, feedback, notifications, and news updates.'),
('dc40', 'vi', 'Nền tảng cộng đồng React Native', 'Nền tảng quản lý cộng đồng cho khu phố và khu dân cư.', null, 'Nền tảng quản lý cộng đồng của VNPT Media cho vận hành khu phố và khu dân cư, gồm họp, công việc, hộ gia đình, cư dân, tài liệu, đánh giá, phản hồi, thông báo và tin tức.'),
('hearme', 'en', 'Android music app', 'Android music streaming with playlists, artists, lyrics, and playback.', null, 'An Android music streaming application that lets users discover artists, manage favorite playlists, and listen to MP3 music.'),
('hearme', 'vi', 'Ứng dụng nghe nhạc Android', 'Ứng dụng nghe nhạc Android với playlist, nghệ sĩ, lời bài hát và playback.', null, 'Ứng dụng nghe nhạc Android cho phép người dùng khám phá nghệ sĩ, quản lý playlist yêu thích và nghe nhạc MP3.'),
('reading-habit', 'en', 'Android reading platform', 'Children''s digital reading platform for stories, comics, audio, and video.', null, 'A children''s digital reading platform developed for KUN LOF, enabling users to explore stories, comics, book series, audiobooks, and videos through an engaging, interactive experience.'),
('reading-habit', 'vi', 'Nền tảng đọc Android', 'Nền tảng đọc số cho trẻ em với truyện, truyện tranh, audio và video.', null, 'Nền tảng đọc số cho trẻ em phát triển cho thương hiệu KUN LOF, cho phép người dùng khám phá truyện, truyện tranh, bộ sách, audiobook và video qua trải nghiệm tương tác thân thiện.')
on conflict (project_slug, locale) do update set
  eyebrow = excluded.eyebrow,
  short_description = excluded.short_description,
  summary_title = excluded.summary_title,
  summary_body = excluded.summary_body;

insert into public.project_technologies (project_slug, technology_slug, sort_order) values
('dp247', 'react-native', 1), ('dp247', 'javascript', 2), ('dp247', 'redux', 3), ('dp247', 'restful-apis', 4), ('dp247', 'git', 5), ('dp247', 'pos-printing', 6),
('huit-edu', 'flutter', 1), ('huit-edu', 'dart', 2), ('huit-edu', 'bloc', 3), ('huit-edu', 'fcm', 4), ('huit-edu', 'restful-apis', 5), ('huit-edu', 'git', 6),
('huit-student', 'flutter', 1), ('huit-student', 'dart', 2), ('huit-student', 'bloc', 3), ('huit-student', 'fcm', 4), ('huit-student', 'restful-apis', 5), ('huit-student', 'git', 6),
('my-dp247', 'react-native', 1), ('my-dp247', 'javascript', 2), ('my-dp247', 'redux', 3), ('my-dp247', 'restful-apis', 4), ('my-dp247', 'maps-location', 5), ('my-dp247', 'git', 6),
('dc40', 'react-native', 1), ('dc40', 'javascript', 2), ('dc40', 'redux', 3), ('dc40', 'restful-apis', 4), ('dc40', 'git', 5),
('hearme', 'kotlin', 1), ('hearme', 'jetpack-compose', 2), ('hearme', 'mvvm', 3), ('hearme', 'firebase', 4), ('hearme', 'restful-apis', 5), ('hearme', 'git', 6),
('reading-habit', 'kotlin', 1), ('reading-habit', 'jetpack-compose', 2), ('reading-habit', 'mvvm', 3), ('reading-habit', 'clean-architecture', 4), ('reading-habit', 'coroutines', 5), ('reading-habit', 'flow', 6), ('reading-habit', 'restful-apis', 7), ('reading-habit', 'retrofit', 8), ('reading-habit', 'git', 9)
on conflict (project_slug, technology_slug) do update set sort_order = excluded.sort_order;

insert into public.project_modules (project_slug, locale, name, is_core, sort_order) values
('dp247', 'en', 'Orders', true, 1),
('dp247', 'en', 'Tables', false, 2),
('dp247', 'en', 'Billing', false, 3),
('dp247', 'en', 'Products', false, 4),
('dp247', 'en', 'Inventory', false, 5),
('dp247', 'en', 'Barcode', false, 6),
('dp247', 'en', 'Receipt Print', false, 7),
('dp247', 'vi', 'Đơn hàng', true, 1),
('dp247', 'vi', 'Bàn', false, 2),
('dp247', 'vi', 'Thanh toán', false, 3),
('dp247', 'vi', 'Sản phẩm', false, 4),
('dp247', 'vi', 'Tồn kho', false, 5),
('dp247', 'vi', 'Barcode', false, 6),
('dp247', 'vi', 'In hóa đơn', false, 7)
on conflict (project_slug, locale, sort_order) do update set
  name = excluded.name,
  is_core = excluded.is_core;

insert into public.project_responsibilities (project_slug, locale, title, body, sort_order) values
('dp247', 'en', 'Core POS modules', 'Built table management, order processing, billing, and product management flows.', 1),
('dp247', 'en', 'Inventory workflows', 'Developed import/export management workflows for goods tracking and stock control.', 2),
('dp247', 'en', 'Customer engagement', 'Implemented promotions and loyalty points to support reward campaigns.', 3),
('dp247', 'en', 'Printer and barcode', 'Integrated receipt printing over Wi-Fi, Bluetooth, USB, and barcode scanning.', 4),
('dp247', 'vi', 'Module POS cốt lõi', 'Xây dựng flow quản lý bàn, xử lý đơn hàng, thanh toán và quản lý sản phẩm.', 1),
('dp247', 'vi', 'Workflow tồn kho', 'Phát triển workflow nhập/xuất hàng để theo dõi hàng hóa và kiểm soát tồn kho.', 2),
('dp247', 'vi', 'Tương tác khách hàng', 'Triển khai khuyến mãi và điểm tích lũy để hỗ trợ campaign reward.', 3),
('dp247', 'vi', 'Máy in và barcode', 'Tích hợp in hóa đơn qua Wi-Fi, Bluetooth, USB và quét barcode.', 4),
('huit-edu', 'en', null, 'Built a mini-app architecture enabling multiple subsystems inside the main application.', 1),
('huit-edu', 'en', null, 'Applied BLoC architecture to separate UI, business logic, and data layers for better maintainability.', 2),
('huit-edu', 'en', null, 'Developed leave requests, absence management, attendance tracking, attendance history, explanations, and adjustment requests.', 3),
('huit-edu', 'en', null, 'Developed task management modules for assigned tasks, progress tracking, deadlines, status, statistics, and reporting.', 4),
('huit-edu', 'vi', null, 'Xây dựng kiến trúc mini-app cho phép nhiều subsystem hoạt động trong một ứng dụng chính.', 1),
('huit-edu', 'vi', null, 'Áp dụng BLoC architecture để tách UI, business logic và data layers nhằm dễ bảo trì.', 2),
('huit-edu', 'vi', null, 'Phát triển leave requests, absence management, chấm công, lịch sử chấm công, giải trình và yêu cầu điều chỉnh.', 3),
('huit-edu', 'vi', null, 'Phát triển module quản lý công việc cho assigned tasks, progress tracking, deadlines, status, statistics và reporting.', 4),
('huit-student', 'en', null, 'Integrated push notifications using Firebase Cloud Messaging (FCM).', 1),
('huit-student', 'en', null, 'Developed feedback list, detail view, feedback submission, survey lists, and survey form functionality.', 2),
('huit-student', 'en', null, 'Applied BLoC architecture and integrated RESTful APIs for user interaction flows.', 3),
('huit-student', 'vi', null, 'Tích hợp push notifications bằng Firebase Cloud Messaging (FCM).', 1),
('huit-student', 'vi', null, 'Phát triển danh sách phản hồi, chi tiết phản hồi, gửi phản hồi, danh sách khảo sát và survey form.', 2),
('huit-student', 'vi', null, 'Áp dụng BLoC architecture và tích hợp RESTful APIs cho user interaction flows.', 3),
('my-dp247', 'en', null, 'Developed product catalog, product detail, promotion, discount, maps, location, ordering, confirmation, and delivery tracking workflows.', 1),
('my-dp247', 'vi', null, 'Phát triển catalog sản phẩm, chi tiết sản phẩm, khuyến mãi, giảm giá, map, location, đặt hàng, xác nhận đơn và theo dõi giao hàng.', 1),
('dc40', 'en', null, 'Implemented dynamic theme customization, meeting management, household and resident management, neighborhood management, notifications, and news features.', 1),
('dc40', 'vi', null, 'Triển khai dynamic theme customization, quản lý cuộc họp, quản lý hộ gia đình và cư dân, quản lý khu dân cư, thông báo và tin tức.', 1),
('hearme', 'en', null, 'Developed Jetpack Compose UI, music discovery screens, song details, social interactions, search, and Firebase-based playback.', 1),
('hearme', 'vi', null, 'Phát triển UI bằng Jetpack Compose, màn hình khám phá nhạc, chi tiết bài hát, tương tác xã hội, tìm kiếm và phát nhạc từ Firebase.', 1),
('reading-habit', 'en', null, 'Built Top Books, search, filtering, content detail pages, domain models, RESTful API integration, and modular reusable components.', 1),
('reading-habit', 'vi', null, 'Xây dựng Top Books, search, filtering, trang chi tiết nội dung, domain models, RESTful API integration và modular reusable components.', 1)
on conflict (project_slug, locale, sort_order) do update set
  title = excluded.title,
  body = excluded.body;
